services:
  - type: web
    name: instaboost-smm-panel
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production tsx server/index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health