services:
  - type: web
    name: smm-panel
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: smm-panel-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

databases:
  - name: smm-panel-db
    databaseName: smm_panel
    user: smm_user
    plan: free