services:
  - type: web
    name: smm-panel
    env: node
    plan: free
    buildCommand: npm ci && npm run build && node fix-production-db.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: RENDER_EXTERNAL_URL
        sync: false
    autoDeploy: false